### ISSUE TITLE
Amount cut off when description is long

### ISSUE THREAD

**Issue by sharmaine1028** [AY2223S1-CS2103T-W17-2/tp#107]
# Problem
When description is long, the amount is cut off from the UI

# Proposed solutions
1. Limit the length of description
2. Expand the `EntryCard` accordingly to the data it contains
3. Make the `EntryCard` scrollable

Personal preference is 1. as I think it would have the benefit of making the UI look neater, even though it is at the expense of  flexibility for the user

However, if we were to do 2. which is our current implementation, we could tweak it such that both description and amount has wrap text functionality and both of them have a fixed width to adhere to.

![image](https://user-images.githubusercontent.com/54767477/198418321-4dbf2072-5cf9-4346-a989-e9fa1c0e663f.png)

**Comment by EmilyOng** [comment]
Handled in https://github.com/AY2223S1-CS2103T-W17-2/tp/pull/155
