### ISSUE TITLE
[PE-D][Tester C] Resizing of windows causes some content to be blocked

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-2/tp#121]
If user tries to adjust the width of the window and the width is too small, some part of the content will be blocked.

![image.png](https://raw.githubusercontent.com/ngshijun/ped/main/files/82a2695e-bffb-4a4b-b6aa-7a9c3d4e6744.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: ngshijun/ped#6

**Comment by EmilyOng** [comment]
Not able to fix in v1.4
